### ISSUE TITLE
Index out of bounds crash, mislabeled tracks if removed tracks present

### ISSUE THREAD

**Issue by Niklink** [leo60228/hsmusicifier#1]
Since hsmusicwiki does not include the Vol. 5, Vol. 8, or Beyond Canon removed tracks in its data, using hsmusicifier on said albums with the removed tracks included will make it crash when it reaches the expected end of the album, but not before applying the wrong metadata to tracks starting with the first removed track. Version 0.3.1, Windows GUI.

**Comment by leo60228** [comment]
This is annoying to fix properly, but I have some ideas.
Not relevant to the issue, but I was unaware that Beyond Canon had removed tracks. Do you have a link?

**Comment by Niklink** [comment]
https://www.youtube.com/watch?v=pXXXTkLMibo originally track 15.

**Comment by leo60228** [comment]
Wait, what? Why was that removed? I liked that track.

**Comment by leo60228** [comment]
*oh*
![image](https://user-images.githubusercontent.com/8355305/106042266-d178e500-60aa-11eb-9619-8c549f83d449.png)

**Comment by leo60228** [comment]
0.3.2 has the closest to a generic solution for this that I can implement, further issues should be opened for specific broken tracks.
Note that artist and track art data for all removed tracks are wrong, this is expected behavior that can't feasibly be fixed without hsmusic including removed tracks.
